<a href="https://colab.research.google.com/github/KevinTheRainmaker/ML_DL_Basics/blob/master/Basic_Skills/Numpy_and_Pandas_Tutorial_with_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy & Pandas Tutorial (feat. Pytorch)
1. Numpy, Array, Matrix
2. Pandas
3. Vector and Matrix using Pytorch

In [2]:
import warnings
warnings.filterwarnings('ignore')

## 1. Numpy, Array, Matrix

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array(['a', 'b', 'c'])
c = np.array([['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c']])

In [5]:
print(type(a), a)
print(type(b), b)
print(type(c), c)

<class 'numpy.ndarray'> [1 2 3]
<class 'numpy.ndarray'> ['a' 'b' 'c']
<class 'numpy.ndarray'> [list(['a']) list(['a', 'b']) list(['a', 'c']) list(['a', 'b', 'c'])]


In [7]:
# fill with 0
print(np.zeros((1,5))) # 1 x 5
print(np.zeros((3,2))) # 3 x 2

[[0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
# fill with 1
print(np.ones((1,5)))
print(np.ones((3,2)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
# np.arange([start, ], stop, [step, ], dtype=None)
print(np.arange(10)) # stop = 10 -> until 9
print(np.arange(3, 7, dtype = np.float)) # start = 3, stop = 7
print(np.arange(3,10,2)) # start = 3, stop = 10, step = 2

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [17]:
# matrix
mat1 = np.array([[1,2,3],[4,5,6]])

# random matrix
mat2 = np.random.randint(low=1, high=10, size=(3,2))
mat3 = np.random.rand(3,2) # Normal distribution (0~1)

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[8 5]
 [8 8]
 [6 1]]
[[0.50657555 0.11903822]
 [0.13380229 0.69833999]
 [0.32196659 0.98364942]]


### Numpy's reshape

In [23]:
mat1 = np.random.rand(6,3)
print(mat1.shape)
print(mat1)

(6, 3)
[[0.60818859 0.35049935 0.51253091]
 [0.83647361 0.92352334 0.74387904]
 [0.89715373 0.64664839 0.02334861]
 [0.20702125 0.23068815 0.47194443]
 [0.7758718  0.10129088 0.06130005]
 [0.04278045 0.93625105 0.28304074]]


In [26]:
# reshape
print(mat1.reshape(2,9).shape)
print(mat1.reshape(2,9))

(2, 9)
[[0.60818859 0.35049935 0.51253091 0.83647361 0.92352334 0.74387904
  0.89715373 0.64664839 0.02334861]
 [0.20702125 0.23068815 0.47194443 0.7758718  0.10129088 0.06130005
  0.04278045 0.93625105 0.28304074]]


In [27]:
# reshape error
print(mat1.reshape(2,5))

ValueError: ignored

In [28]:
# -1:all
print(mat1.reshape(1,-1).shape)
print(mat1.reshape(1,-1))

print()

print(mat1.reshape(-1,1).shape)
print(mat1.reshape(-1,1))

(1, 18)
[[0.60818859 0.35049935 0.51253091 0.83647361 0.92352334 0.74387904
  0.89715373 0.64664839 0.02334861 0.20702125 0.23068815 0.47194443
  0.7758718  0.10129088 0.06130005 0.04278045 0.93625105 0.28304074]]

(18, 1)
[[0.60818859]
 [0.35049935]
 [0.51253091]
 [0.83647361]
 [0.92352334]
 [0.74387904]
 [0.89715373]
 [0.64664839]
 [0.02334861]
 [0.20702125]
 [0.23068815]
 [0.47194443]
 [0.7758718 ]
 [0.10129088]
 [0.06130005]
 [0.04278045]
 [0.93625105]
 [0.28304074]]


In [35]:
# to tensor
print(mat1.reshape(3,2,3).shape) # depth, row, column
print(mat1.reshape(3,2,3))

(3, 2, 3)
[[[0.60818859 0.35049935 0.51253091]
  [0.83647361 0.92352334 0.74387904]]

 [[0.89715373 0.64664839 0.02334861]
  [0.20702125 0.23068815 0.47194443]]

 [[0.7758718  0.10129088 0.06130005]
  [0.04278045 0.93625105 0.28304074]]]


### Numpy Slicing

In [40]:
# slicing
mat2 = np.arange(24).reshape(-1,4)
print(mat2)

print()
print('-Slicing #1-')
print(mat2[:2,:3]) # slice (row 0 ~ row 1, col0 ~ col 2)
print()
print('-Slicing #2-')
print(mat2[3,1:3]) # slice (row 3, col 1 ~ col 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

-Slicing #1-
[[0 1 2]
 [4 5 6]]

-Slicing #2-
[13 14]


### Math Arithmetic Operations

In [42]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([[9,8,7], [6,5,4], [3,2,1]])

print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [43]:
x+y

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [44]:
x-y

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [45]:
x * y # Not a Matrix factorization

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [46]:
x / y

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [48]:
# power
print(x ** 2)
print(np.power(x, 2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [50]:
# dot product
np.dot(x,y)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [51]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [55]:
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

x * z1 # Again, Not a Matrix factorization

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [57]:
# shape error
x * z2

ValueError: ignored

In [59]:
# sum
print(x)
print(x.sum(axis = 0)) # row direct(perpendicular) sum
print(x.sum(axis = 1)) # col direct(parallel) sum

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [60]:
# mean
print(x)
print(x.mean(axis = 0))
print(x.mean(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[2. 5. 8.]


In [61]:
# standard deviation
print(x)
print(x.std(axis = 0))
print(x.std(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [62]:
# Transpose
print(x)
print(x.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [64]:
# dot production with  matrix
print(np.dot(x, z1.T)) # (3 x 3) * (3 x 1)

[[12]
 [30]
 [48]]


In [65]:
# sort
xx = np.random.rand(15)
print(xx)
print(xx.argsort()) # index
xx.sort() # operation, not a matrix
print(xx) 

[0.32873852 0.72307857 0.94141842 0.46124621 0.20953482 0.14997091
 0.08007432 0.02419033 0.60544897 0.51023431 0.3642639  0.35954217
 0.77393627 0.98047631 0.99125569]
[ 7  6  5  4  0 11 10  3  9  8  1 12  2 13 14]
[0.02419033 0.08007432 0.14997091 0.20953482 0.32873852 0.35954217
 0.3642639  0.46124621 0.51023431 0.60544897 0.72307857 0.77393627
 0.94141842 0.98047631 0.99125569]


## 2. Pandas

In [66]:
import pandas as pd

### Pandas Series

1-dimensional

In [79]:
pd_series = pd.Series(index = ['a','b','c','d','e'], data = [1,2,3,4,5])
pd_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [80]:
# Basic information od Pandas Series
print('Dimension: ', pd_series.ndim)
print('Shape: ', pd_series.shape)
print('Num of values: ', pd_series.size)

print('Value: ', pd_series.values)
print('Index: ', pd_series.index)

Dimension:  1
Shape:  (5,)
Num of values:  5
Value:  [1 2 3 4 5]
Index:  Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


### Data Search using Index

In [81]:
# loc: using index
print(pd_series.loc['a']) # need to know exact index name
print(pd_series.loc[['a','c']]) # also return index 

# iloc: integer location
print(pd_series.iloc[0]) 
print(pd_series.iloc[[0,2]])

1
a    1
c    3
dtype: int64
1
a    1
c    3
dtype: int64


### Data Deletion

In [82]:
print(pd_series.drop('b')) # this is temporal deletion
print(pd_series)

a    1
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [83]:
print(pd_series.drop('b', inplace = True)) # Permanetly delete / return None
print(pd_series)

None
a    1
c    3
d    4
e    5
dtype: int64


### Pandas Dataframe
2-dimensional with row and column

In [84]:
data = {
    'A': np.arange(15),
    'B': np.random.randint(low = 0, high=15, size=(15)),
    'C': np.random.rand(15)
}

data_df = pd.DataFrame(data)

In [86]:
data

{'A': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 'B': array([11,  5, 12,  7,  3,  8,  2,  8,  3, 10, 12,  2, 14,  0,  5]),
 'C': array([0.88160205, 0.94700086, 0.35950562, 0.41730802, 0.40457515,
        0.69134546, 0.52619972, 0.88022951, 0.4551784 , 0.76586572,
        0.63300851, 0.56066883, 0.00693194, 0.77269799, 0.88190167])}

In [85]:
data_df

A   B         C
0    0  11  0.881602
1    1   5  0.947001
2    2  12  0.359506
3    3   7  0.417308
4    4   3  0.404575
5    5   8  0.691345
6    6   2  0.526200
7    7   8  0.880230
8    8   3  0.455178
9    9  10  0.765866
10  10  12  0.633009
11  11   2  0.560669
12  12  14  0.006932
13  13   0  0.772698
14  14   5  0.881902

### Slicing


In [87]:
data_df[1:3]

A   B         C
1  1   5  0.947001
2  2  12  0.359506

In [88]:
data_df.loc[1]

A    1.000000
B    5.000000
C    0.947001
Name: 1, dtype: float64

In [89]:
data_df.loc[1]['C']

0.9470008637941099

In [90]:
data_df.loc[1][['B','C']]

B    5.000000
C    0.947001
Name: 1, dtype: float64

### Add, Remove, Sort

In [91]:
data_df['D'] = data_df['A'] >= 5
data_df

A   B         C      D
0    0  11  0.881602  False
1    1   5  0.947001  False
2    2  12  0.359506  False
3    3   7  0.417308  False
4    4   3  0.404575  False
5    5   8  0.691345   True
6    6   2  0.526200   True
7    7   8  0.880230   True
8    8   3  0.455178   True
9    9  10  0.765866   True
10  10  12  0.633009   True
11  11   2  0.560669   True
12  12  14  0.006932   True
13  13   0  0.772698   True
14  14   5  0.881902   True

In [92]:
data_df.drop('D', axis = 1, inplace = True)

In [93]:
data_df.sort_index(axis=0, ascending=False)

A   B         C
14  14   5  0.881902
13  13   0  0.772698
12  12  14  0.006932
11  11   2  0.560669
10  10  12  0.633009
9    9  10  0.765866
8    8   3  0.455178
7    7   8  0.880230
6    6   2  0.526200
5    5   8  0.691345
4    4   3  0.404575
3    3   7  0.417308
2    2  12  0.359506
1    1   5  0.947001
0    0  11  0.881602

## 3. Vector and Matrix using Pytorch

- Pytorch
  - provides multidimensional arrays
  - tensors, and an extensive library of operations on them

In [1]:
import torch

### Tensor
Mltidimensional arrays

In [97]:
# Create a `torch.Tensor` object with the given data
# It is a 1D vector
V_data = [1., 2., 3.] # np.float
V = torch.Tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [98]:
# Create a matrix
M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.Tensor(M_data)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [100]:
# Create a 3D tensor of size 2x2x2
T_data = [[[1., 2.], [3.,4.]],
          [[5., 6.], [7., 8.]]]
T = torch.Tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [101]:
# torch.zeros
a = torch.zeros(4)
print(a)

b = torch.zeros(5, 2, 3)
print(b)

tensor([0., 0., 0., 0.])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [102]:
# torch.ones
c = torch.ones(3)
print(c)

d = torch.ones(2, 3)
print(d)

tensor([1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [103]:
# Initialize with random numbers
x = torch.rand(5, 3)
print(x)

# Initialize with memory's values
x = torch.empty(5, 3)
print(x)

tensor([[0.0404, 0.5206, 0.4792],
        [0.9775, 0.9961, 0.5452],
        [0.6464, 0.4594, 0.3336],
        [0.7901, 0.5796, 0.3270],
        [0.3113, 0.3559, 0.9988]])
tensor([[ 2.4623e+00,  3.0697e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  1.0000e+00],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22, -4.5138e-17]])


In [104]:
# Set rand type
rand_double = torch.rand(4, dtype=torch.double)
print(rand_double)

rand_float = torch.rand(2, 3, dtype=torch.float)
print(rand_float)

tensor([0.4113, 0.2611, 0.8390, 0.2588], dtype=torch.float64)
tensor([[0.8740, 0.4929, 0.8078],
        [0.9523, 0.6128, 0.9111]])


In [106]:
# size
print(rand_float.size())

torch.Size([2, 3])


### Indexing Tensors

In [109]:
temp = torch.Tensor([0, 1, 2, 3, 4, 5, 6, 7])

print(temp[:]) # all tensor elements
print(temp[1:4]) # index 1~3
print(temp[1:6:2]) # index 1, 3, 5

tensor([0., 1., 2., 3., 4., 5., 6., 7.])
tensor([1., 2., 3.])
tensor([1., 3., 5.])


In [117]:
temp = torch.Tensor([[0, 1, 2], [3, 4, 5]])

print(temp) # all tensor elements
print(temp[1:, 1:]) # row 1 / col 1~2
print(temp[0:, 0]) # row 0~1 / col 0

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[4., 5.]])
tensor([0., 3.])


### Tensor elements types

add `dtype` argument to tensor contructors
-> specify the data type that will be contained in the tensor
  - possible values the tensor can hold (int, float, ...)
  - number of bytes per value (8, 16, 32, ...)

ex)
  - torch.float32 (=`torch.float`): 32-bit floating point (**default**)
  - torch.float64 (=`torch.double`): 64-bit double-precision floating point
  - torch.float16 (=`torch.half`): 16-bit half-precision floating point
  - torch.int32 (=`torch.int`): 32-bit integers
  - torch.int64 (=`torch.long`): 64-bit integers
  - torch.bool: Boolean

In [119]:
default_points = torch.Tensor([2,2])
float_points = torch.ones(5, 2, dtype = torch.float32)
int_points = torch.zeros(3, dtype = torch.int64)

print(default_points)
print(float_points)
print(int_points)

tensor([2., 2.])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([0, 0, 0])


In [120]:
# find out dtype
print(default_points.dtype)
print(float_points.dtype)
print(int_points.dtype)

torch.float32
torch.float32
torch.int64


In [121]:
# Change dtype

to_int_1 = float_points.int()
print(to_int_1.dtype)

to_int_2 = float_points.to(torch.int64)
print(to_int_2.dtype)

torch.int32
torch.int64


### The Tensor API

Almost operations that related to tensor is implemented in torch module

ex)
  - math operations: `abs`, `cos`, `mean`, `std`, `norm`, `equal`, `max`, ...
  - tensor element-wise sum, concat, ...
  - random sampling: `random`, `normal`, ... 

### Tensor Shape and Reshape

In [122]:
# shape: Returns the size of the tensor
a = torch.Tensor([[1,2,3], [4,5,6]])

print(a)
print(a.shape)
print(a.size())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
torch.Size([2, 3])


In [123]:
# Reshape: bring data from original tensor using shape and reshape it

a_reshape = a.reshape(3,2)
print(a_reshape)
print(a_reshape.shape)

a_reshape = a.reshape(-1, 2) # the size -1 is inferred from other dimensions
print(a_reshape)
print(a_reshape.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])


In [128]:
# reshape error: not compatible with the current shape
a_reshape_error = a.reshape(-1, 4)

RuntimeError: ignored

In [131]:
# View: Returns a new tensor with the same data as the original tensor but of a different shape
# simillar use with reshape

x = torch.randn(4, 4)
print(x.size())
print(x)

y = x.view(16)
print(y.size())
print(y)

z = x.view(-1, 8)
print(z.size())
print(z)

torch.Size([4, 4])
tensor([[ 0.3574, -1.2198, -0.9631,  1.9785],
        [ 0.5627, -0.6565, -0.1029, -0.1425],
        [-0.0190,  1.9459,  1.2319,  0.1178],
        [ 0.4212, -1.1725,  0.9406,  0.4748]])
torch.Size([16])
tensor([ 0.3574, -1.2198, -0.9631,  1.9785,  0.5627, -0.6565, -0.1029, -0.1425,
        -0.0190,  1.9459,  1.2319,  0.1178,  0.4212, -1.1725,  0.9406,  0.4748])
torch.Size([2, 8])
tensor([[ 0.3574, -1.2198, -0.9631,  1.9785,  0.5627, -0.6565, -0.1029, -0.1425],
        [-0.0190,  1.9459,  1.2319,  0.1178,  0.4212, -1.1725,  0.9406,  0.4748]])


### Transpose

In [142]:
x = torch.randn(2,3)
print(x)

print('\n- Transpose -\n')
print(x.t())
print(torch.t(x))
print(torch.transpose(x, 1, 0)) # transpose(input, dim0, dim1)

tensor([[ 0.9023, -1.1338, -1.2363],
        [ 0.8408, -1.1034,  1.7478]])

- Transpose -

tensor([[ 0.9023,  0.8408],
        [-1.1338, -1.1034],
        [-1.2363,  1.7478]])
tensor([[ 0.9023,  0.8408],
        [-1.1338, -1.1034],
        [-1.2363,  1.7478]])
tensor([[ 0.9023,  0.8408],
        [-1.1338, -1.1034],
        [-1.2363,  1.7478]])


In [143]:
# more complex case
real_example = torch.randn(64, 128, 768)
print(real_example.shape)

transposed = torch.transpose(real_example, 1, 2)
print(transposed.shape)

torch.Size([64, 128, 768])
torch.Size([64, 768, 128])


### Operations

In [144]:
x = torch.ones(1, 2)
print(x)

y = torch.ones(5, 3)
print(y)

tensor([[1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [146]:
# error
print(x+y)

RuntimeError: ignored

In [147]:
y = torch.ones(5, 2)
print(y)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [150]:
# 1.
print(x+y)

# 2.
print(torch.add(x,y))

# 3.
result = torch.empty(5, 2)
torch.add(x, y, out = result) # fill the space: learning
print(result)

# 4.
print(y.add_(x)) # inplace

tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]])
tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]])
tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]])
tensor([[4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.],
        [4., 4.]])


## Ref: Moving tensors to the GPU

In [2]:
torch.cuda.is_available()

True

In [3]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device = 'cuda')
print(points_gpu)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')


In [12]:
points = torch.randn(2,3)
points_gpu = points.to(device='cuda')

print(points_gpu)

tensor([[-0.9133,  2.1713,  1.7431],
        [ 1.4548, -0.5467, -0.4414]], device='cuda:0')


If pur machine has more than one GPU, we can also decide on which GPU we allocate the tensor by passing a zero-based integer identifying the GPU in the machine, such as `cuda:0`, `cuda:1`, ... 

In [13]:
points_gpu_0 = points.to(device = 'cuda:0')
print(points_gpu_0)

tensor([[-0.9133,  2.1713,  1.7431],
        [ 1.4548, -0.5467, -0.4414]], device='cuda:0')


In [14]:
# operations performed on CPU and GPU

%time points_op_cpu = 2 * points # on CPU
print(points_op_cpu)

%time points_op_gpu = 2 * points.to(device = 'cuda') # on GPU
print(points_op_gpu)

CPU times: user 922 µs, sys: 0 ns, total: 922 µs
Wall time: 930 µs
tensor([[-1.8266,  4.3425,  3.4862],
        [ 2.9095, -1.0933, -0.8829]])
CPU times: user 223 µs, sys: 0 ns, total: 223 µs
Wall time: 231 µs
tensor([[-1.8266,  4.3425,  3.4862],
        [ 2.9095, -1.0933, -0.8829]], device='cuda:0')


In [15]:
# move the tensor back to the CPU

points_cpu = points_gpu_0.to(device='cpu')
print(points_cpu)
print(points_cpu.device)

tensor([[-0.9133,  2.1713,  1.7431],
        [ 1.4548, -0.5467, -0.4414]])
cpu


In [18]:
# shorter forms
points_gpu = points.cuda()
print(points_gpu)

points_gpu = points.cuda(0)
print(points_gpu)

points_cpu = points_gpu.cpu()
print(points_cpu)

tensor([[-0.9133,  2.1713,  1.7431],
        [ 1.4548, -0.5467, -0.4414]], device='cuda:0')
tensor([[-0.9133,  2.1713,  1.7431],
        [ 1.4548, -0.5467, -0.4414]], device='cuda:0')
tensor([[-0.9133,  2.1713,  1.7431],
        [ 1.4548, -0.5467, -0.4414]])


### Numpy Interpretability
PyTorch tensors can be convered to NumPy arrays and vice versa efficiently

In [19]:
# tensor to numpy array
points = torch.ones(3, 4)
points_np = points.numpy()

print(points_np)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
type(points_np)

numpy.ndarray

In [20]:
# numpy array to tensor
points = torch.from_numpy(points_np)
print(points)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [22]:
type(points)

torch.Tensor

### Save and load tensors
save tensors to a file and load them back at some point

PyTorch uses pickle under the hood to serialize the tensor object, plus dedicated serialization code for the storage.

In [24]:
print(points)

torch.save(points, './points_temp.t')

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [25]:
load_points = torch.load('./points_temp.t')
print(load_points)
print(type(load_points))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
<class 'torch.Tensor'>
