<a href="https://colab.research.google.com/github/KevinTheRainmaker/ML_DL_Basics/blob/master/Numpy_and_Pandas_Tutorial_with_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy & Pandas Tutorial (feat. Pytorch)
1. Numpy, Array, Matrix
2. Pandas
3. Vector and Matrix using Pytorch

In [2]:
import warnings
warnings.filterwarnings('ignore')

## 1. Numpy, Array, Matrix

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array(['a', 'b', 'c'])
c = np.array([['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c']])

In [5]:
print(type(a), a)
print(type(b), b)
print(type(c), c)

<class 'numpy.ndarray'> [1 2 3]
<class 'numpy.ndarray'> ['a' 'b' 'c']
<class 'numpy.ndarray'> [list(['a']) list(['a', 'b']) list(['a', 'c']) list(['a', 'b', 'c'])]


In [7]:
# fill with 0
print(np.zeros((1,5))) # 1 x 5
print(np.zeros((3,2))) # 3 x 2

[[0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
# fill with 1
print(np.ones((1,5)))
print(np.ones((3,2)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
# np.arange([start, ], stop, [step, ], dtype=None)
print(np.arange(10)) # stop = 10 -> until 9
print(np.arange(3, 7, dtype = np.float)) # start = 3, stop = 7
print(np.arange(3,10,2)) # start = 3, stop = 10, step = 2

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [17]:
# matrix
mat1 = np.array([[1,2,3],[4,5,6]])

# random matrix
mat2 = np.random.randint(low=1, high=10, size=(3,2))
mat3 = np.random.rand(3,2) # Normal distribution (0~1)

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[8 5]
 [8 8]
 [6 1]]
[[0.50657555 0.11903822]
 [0.13380229 0.69833999]
 [0.32196659 0.98364942]]


### Numpy's reshape

In [23]:
mat1 = np.random.rand(6,3)
print(mat1.shape)
print(mat1)

(6, 3)
[[0.60818859 0.35049935 0.51253091]
 [0.83647361 0.92352334 0.74387904]
 [0.89715373 0.64664839 0.02334861]
 [0.20702125 0.23068815 0.47194443]
 [0.7758718  0.10129088 0.06130005]
 [0.04278045 0.93625105 0.28304074]]


In [26]:
# reshape
print(mat1.reshape(2,9).shape)
print(mat1.reshape(2,9))

(2, 9)
[[0.60818859 0.35049935 0.51253091 0.83647361 0.92352334 0.74387904
  0.89715373 0.64664839 0.02334861]
 [0.20702125 0.23068815 0.47194443 0.7758718  0.10129088 0.06130005
  0.04278045 0.93625105 0.28304074]]


In [27]:
# reshape error
print(mat1.reshape(2,5))

ValueError: ignored

In [28]:
# -1:all
print(mat1.reshape(1,-1).shape)
print(mat1.reshape(1,-1))

print()

print(mat1.reshape(-1,1).shape)
print(mat1.reshape(-1,1))

(1, 18)
[[0.60818859 0.35049935 0.51253091 0.83647361 0.92352334 0.74387904
  0.89715373 0.64664839 0.02334861 0.20702125 0.23068815 0.47194443
  0.7758718  0.10129088 0.06130005 0.04278045 0.93625105 0.28304074]]

(18, 1)
[[0.60818859]
 [0.35049935]
 [0.51253091]
 [0.83647361]
 [0.92352334]
 [0.74387904]
 [0.89715373]
 [0.64664839]
 [0.02334861]
 [0.20702125]
 [0.23068815]
 [0.47194443]
 [0.7758718 ]
 [0.10129088]
 [0.06130005]
 [0.04278045]
 [0.93625105]
 [0.28304074]]


In [35]:
# to tensor
print(mat1.reshape(3,2,3).shape) # depth, row, column
print(mat1.reshape(3,2,3))

(3, 2, 3)
[[[0.60818859 0.35049935 0.51253091]
  [0.83647361 0.92352334 0.74387904]]

 [[0.89715373 0.64664839 0.02334861]
  [0.20702125 0.23068815 0.47194443]]

 [[0.7758718  0.10129088 0.06130005]
  [0.04278045 0.93625105 0.28304074]]]


### Numpy Slicing

In [40]:
# slicing
mat2 = np.arange(24).reshape(-1,4)
print(mat2)

print()
print('-Slicing #1-')
print(mat2[:2,:3]) # slice (row 0 ~ row 1, col0 ~ col 2)
print()
print('-Slicing #2-')
print(mat2[3,1:3]) # slice (row 3, col 1 ~ col 2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

-Slicing #1-
[[0 1 2]
 [4 5 6]]

-Slicing #2-
[13 14]


### Math Arithmetic Operations

In [42]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([[9,8,7], [6,5,4], [3,2,1]])

print(x)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [43]:
x+y

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [44]:
x-y

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [45]:
x * y # Not a Matrix factorization

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [46]:
x / y

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [48]:
# power
print(x ** 2)
print(np.power(x, 2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [50]:
# dot product
np.dot(x,y)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [51]:
np.sqrt(x)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [55]:
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

x * z1 # Again, Not a Matrix factorization

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [57]:
# shape error
x * z2

ValueError: ignored

In [59]:
# sum
print(x)
print(x.sum(axis = 0)) # row direct(perpendicular) sum
print(x.sum(axis = 1)) # col direct(parallel) sum

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [60]:
# mean
print(x)
print(x.mean(axis = 0))
print(x.mean(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4. 5. 6.]
[2. 5. 8.]


In [61]:
# standard deviation
print(x)
print(x.std(axis = 0))
print(x.std(axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]


In [62]:
# Transpose
print(x)
print(x.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [64]:
# dot production with  matrix
print(np.dot(x, z1.T)) # (3 x 3) * (3 x 1)

[[12]
 [30]
 [48]]


In [65]:
# sort
xx = np.random.rand(15)
print(xx)
print(xx.argsort()) # index
xx.sort() # operation, not a matrix
print(xx) 

[0.32873852 0.72307857 0.94141842 0.46124621 0.20953482 0.14997091
 0.08007432 0.02419033 0.60544897 0.51023431 0.3642639  0.35954217
 0.77393627 0.98047631 0.99125569]
[ 7  6  5  4  0 11 10  3  9  8  1 12  2 13 14]
[0.02419033 0.08007432 0.14997091 0.20953482 0.32873852 0.35954217
 0.3642639  0.46124621 0.51023431 0.60544897 0.72307857 0.77393627
 0.94141842 0.98047631 0.99125569]


## 2. Pandas

In [66]:
import pandas as pd

### Pandas Series

1-dimensional

In [79]:
pd_series = pd.Series(index = ['a','b','c','d','e'], data = [1,2,3,4,5])
pd_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [80]:
# Basic information od Pandas Series
print('Dimension: ', pd_series.ndim)
print('Shape: ', pd_series.shape)
print('Num of values: ', pd_series.size)

print('Value: ', pd_series.values)
print('Index: ', pd_series.index)

Dimension:  1
Shape:  (5,)
Num of values:  5
Value:  [1 2 3 4 5]
Index:  Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


### Data Search using Index

In [81]:
# loc: using index
print(pd_series.loc['a']) # need to know exact index name
print(pd_series.loc[['a','c']]) # also return index 

# iloc: integer location
print(pd_series.iloc[0]) 
print(pd_series.iloc[[0,2]])

1
a    1
c    3
dtype: int64
1
a    1
c    3
dtype: int64


### Data Deletion

In [82]:
print(pd_series.drop('b')) # this is temporal deletion
print(pd_series)

a    1
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [83]:
print(pd_series.drop('b', inplace = True)) # Permanetly delete / return None
print(pd_series)

None
a    1
c    3
d    4
e    5
dtype: int64


### Pandas Dataframe
2-dimensional with row and column

In [84]:
data = {
    'A': np.arange(15),
    'B': np.random.randint(low = 0, high=15, size=(15)),
    'C': np.random.rand(15)
}

data_df = pd.DataFrame(data)

In [86]:
data

{'A': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]),
 'B': array([11,  5, 12,  7,  3,  8,  2,  8,  3, 10, 12,  2, 14,  0,  5]),
 'C': array([0.88160205, 0.94700086, 0.35950562, 0.41730802, 0.40457515,
        0.69134546, 0.52619972, 0.88022951, 0.4551784 , 0.76586572,
        0.63300851, 0.56066883, 0.00693194, 0.77269799, 0.88190167])}

In [85]:
data_df

A   B         C
0    0  11  0.881602
1    1   5  0.947001
2    2  12  0.359506
3    3   7  0.417308
4    4   3  0.404575
5    5   8  0.691345
6    6   2  0.526200
7    7   8  0.880230
8    8   3  0.455178
9    9  10  0.765866
10  10  12  0.633009
11  11   2  0.560669
12  12  14  0.006932
13  13   0  0.772698
14  14   5  0.881902

### Slicing


In [87]:
data_df[1:3]

A   B         C
1  1   5  0.947001
2  2  12  0.359506

In [88]:
data_df.loc[1]

A    1.000000
B    5.000000
C    0.947001
Name: 1, dtype: float64

In [89]:
data_df.loc[1]['C']

0.9470008637941099

In [90]:
data_df.loc[1][['B','C']]

B    5.000000
C    0.947001
Name: 1, dtype: float64

### Add, Remove, Sort

In [91]:
data_df['D'] = data_df['A'] >= 5
data_df

A   B         C      D
0    0  11  0.881602  False
1    1   5  0.947001  False
2    2  12  0.359506  False
3    3   7  0.417308  False
4    4   3  0.404575  False
5    5   8  0.691345   True
6    6   2  0.526200   True
7    7   8  0.880230   True
8    8   3  0.455178   True
9    9  10  0.765866   True
10  10  12  0.633009   True
11  11   2  0.560669   True
12  12  14  0.006932   True
13  13   0  0.772698   True
14  14   5  0.881902   True

In [92]:
data_df.drop('D', axis = 1, inplace = True)

In [93]:
data_df.sort_index(axis=0, ascending=False)

A   B         C
14  14   5  0.881902
13  13   0  0.772698
12  12  14  0.006932
11  11   2  0.560669
10  10  12  0.633009
9    9  10  0.765866
8    8   3  0.455178
7    7   8  0.880230
6    6   2  0.526200
5    5   8  0.691345
4    4   3  0.404575
3    3   7  0.417308
2    2  12  0.359506
1    1   5  0.947001
0    0  11  0.881602

## 3. Vector and Matrix using Pytorch