<a href="https://colab.research.google.com/github/KevinTheRainmaker/ML_DL_Basics/blob/master/Udacity%3A%20Intro%20to%20TensorFlow%20for%20DL/TFSD_S1L1_Colab0_Intro_to_Colab_and_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Functions, Conditionals, and Interation

In [3]:
def HelloWorldXY(x,y):
  if (x<10):
    print('Hello World, x was < 10')
  elif (x<20):
    print('Hello World, x was >= 10 but < 20')
  else:
    print('Hello World, x was >= 20')
  return x+y

for i in range(8, 25, 5):
  print('--- Now running with i: {}'.format(i))
  r = HelloWorldXY(i,i)
  print('Result from HelloWorld: {}'.format(i,r))

--- Now running with i: 8
Hello World, x was < 10
Result from HelloWorld: 8
--- Now running with i: 13
Hello World, x was >= 10 but < 20
Result from HelloWorld: 13
--- Now running with i: 18
Hello World, x was >= 10 but < 20
Result from HelloWorld: 18
--- Now running with i: 23
Hello World, x was >= 20
Result from HelloWorld: 23


# Numpy and lists
Numpy gives you a lot's of support functions that are useful when doing ML

In [10]:
import numpy as np

a = np.array(['Hello', 'World'])
a = np.append(a, '!')
print(a,'\n')
print('Each Element in "a"')
for i in a:
  print(i)

print('\nEach Element and their index')
for i,e in enumerate(a):
  print(i,e)

['Hello' 'World' '!'] 

Each Element in "a"
Hello
World
!

Each Element and their index
0 Hello
1 World
2 !


In [11]:
b = np.array([0,1,4,3,2])
print(f'Max: {np.max(b)}')
print(f'Average: {np.average(b)}')
print(f'Max index: {np.argmax(b)}')

Max: 4
Average: 2.0
Max index: 2


In [13]:
print(f'Type of b: {type(b)}\nType of b[0]: {type(b[0])}')

Type of b: <class 'numpy.ndarray'>
Type of b[0]: <class 'numpy.int64'>


In [14]:
print('Use Numpy to create a [3,3] dimension array with random number')
c = np.random.rand(3,3)
print(c)

Use Numpy to create a [3,3] dimension array with random number
[[0.32507081 0.52021407 0.23098362]
 [0.80328695 0.79137352 0.48801952]
 [0.60385637 0.21953683 0.75181035]]


In [16]:
print('Dimension of Array')
print(a.shape)
print(b.shape)
print(c.shape)

Dimension of Array
(3,)
(5,)
(3, 3)
